name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout # 步骤1
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Use Node.js # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      - run: npm install --frozen-lockfile
      - name: Build
        run: npm run docs:build

      - name: Deploy Github
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist

      - name: deploy My Server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: "root" #ssh user name
          port: "22" # 远程服务器ssh端口，默认22
          server: "111.230.199.157" # 远程服务器IP
          password: ${{ secrets.FTP_PASSWORD }}
          # ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # 认证服务器秘钥对的私钥
          local_path: "docs/.vuepress/dist/*" # 对应我们项目打包后的静态文件路径
          remote_path: "/www/web/record" # 服务器上的路径

