name: DeployAli

on:
  push:
    branches:
      - main

env:
  TARGET_DIR: /www/web/love
  NODE_VERSION: 20.x

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy Github Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Deploy Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "ssh scp ssh pipelines CPP Love server"
          LASTSSH: "after copying"
        with:
          host: "47.101.50.136"
          user: "root"
          pass: ${{ secrets.ALI_PASSWORD }}
          connect_timeout: 20s
          first_ssh: |-
            rm -rf $TARGET_DIR
            echo $WELCOME
            mkdir -p $TARGET_DIR
          scp: |-
            './dist/*' => $TARGET_DIR/
          last_ssh: |-
            echo $LASTSSH
