name: DeployAli

on:
  push:
    branches:
      - main

env:
  TARGET_DIR: /www/web/love
  NODE_VERSION: 18.x

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fix apt sources
        run: |
          sudo rm -rf /var/lib/apt/lists/*
          sudo sed -i 's|http://archive.ubuntu.com|https://mirrors.aliyun.com|g' /etc/apt/sources.list

      - name: Install dependencies with retry
        run: |
          for i in {1..3}; do
            sudo apt-get update -y
            sudo apt-get install -y ca-certificates openssh-client openssl sshpass
            if [ $? -eq 0 ]; then
              break
            else
              sleep 10
            fi
          done
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy Github Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Deploy Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.0.0
        env:
          WELCOME: "ssh scp ssh pipelines CPP Love server"
          LASTSSH: "after copying"
        with:
          host: "47.101.50.136"
          user: "root"
          pass: ${{ secrets.ALI_PASSWORD }}
          connect_timeout: 20s
          first_ssh: |
            rm -rf $TARGET_DIR
            mkdir -p $TARGET_DIR
          scp: |
            './dist/*' => $TARGET_DIR/
          last_ssh: |
            echo $LASTSSH
