name: DeployAli

on:
  push:
    branches:
      - main

env:
  TARGET_DIR: /www/web/love
  NODE_VERSION: 20.x

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 步骤1
        uses: actions/checkout@v4 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Use Node.js # 步骤2
        uses: actions/setup-node@v4 # 作用：安装nodejs
        with:
          node-version: ${{ env.NODE_VERSION }} # 版本
      - run: npm install
      - name: Build
        run: npm run build

      - name: Deploy Github Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Deploy Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "ssh scp ssh pipelines CPP Love server"
          LASTSSH: "after copying"
        with:
          host: "47.101.50.136"
          user: "root"
          pass: ${{ secrets.ALI_PASSWORD }}
          connect_timeout: 20s
          first_ssh: |-
            rm -rf $TARGET_DIR
            echo $WELCOME
            mkdir -p $TARGET_DIR
          scp: |-
            './dist/*' => $TARGET_DIR/
          last_ssh: |-
            echo $LASTSSH
